using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace NesCollector.Data.Migrations
{
    public partial class init : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Games",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    ApiGameId = table.Column<string>(nullable: true),
                    SystemId = table.Column<string>(nullable: true),
                    Title = table.Column<string>(nullable: true),
                    Genre = table.Column<string>(nullable: true),
                    CoverURL = table.Column<string>(nullable: true),
                    Upc = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Games", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Email = table.Column<string>(nullable: true),
                    Username = table.Column<string>(nullable: true),
                    FirstName = table.Column<string>(nullable: true),
                    LastName = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UserGames",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Title = table.Column<string>(nullable: true),
                    Genre = table.Column<string>(nullable: true),
                    SystemId = table.Column<string>(nullable: true),
                    Condition = table.Column<string>(nullable: true),
                    HasBox = table.Column<bool>(nullable: false),
                    HasManual = table.Column<bool>(nullable: false),
                    IsCIB = table.Column<bool>(nullable: false),
                    Value = table.Column<double>(nullable: false),
                    UserId = table.Column<int>(nullable: false),
                    GameId = table.Column<int>(nullable: false),
                    GameId1 = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserGames", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserGames_Games_GameId1",
                        column: x => x.GameId1,
                        principalTable: "Games",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_UserGames_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Wishlists",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Title = table.Column<string>(nullable: true),
                    Genre = table.Column<string>(nullable: true),
                    SystemId = table.Column<string>(nullable: true),
                    MaxPrice = table.Column<double>(nullable: false),
                    UserId = table.Column<int>(nullable: false),
                    GameId = table.Column<int>(nullable: false),
                    GameId1 = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Wishlists", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Wishlists_Games_GameId1",
                        column: x => x.GameId1,
                        principalTable: "Games",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Wishlists_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Games",
                columns: new[] { "Id", "ApiGameId", "CoverURL", "Genre", "SystemId", "Title", "Upc" },
                values: new object[,]
                {
                    { "1  ", "12168", null, "Football", "NES", "10-Yard Fight", null },
                    { "599", "12369", null, "Puzzle", "NES", "Qix", null },
                    { "600", "12371", null, "Action & Adventure", "NES", "Quattro Adventure", null },
                    { "601", "39524", null, "Action & Adventure", "NES", "Quattro Adventure [Aladdin]", null },
                    { "602", "19308", null, "Arcade", "NES", "Quattro Arcade", null },
                    { "603", "12372", null, "Sports", "NES", "Quattro Sports", null },
                    { "604", "39525", null, "Sports", "NES", "Quattro Sports [Aladdin]", null },
                    { "605", "21024", null, "Controllers", "NES", "Quickshot Joystick", null },
                    { "606", "16260", null, "Accessories", "NES", "Quickshot Sighting Scope", null },
                    { "607", "9635", null, "Baseball", "NES", "RBI Baseball", null },
                    { "608", "12373", null, "Baseball", "NES", "RBI Baseball 2", null },
                    { "609", "12374", null, "Baseball", "NES", "RBI Baseball 3", null },
                    { "598", "12368", null, "Arcade", "NES", "Q*bert", null },
                    { "610", "39512", null, "Baseball", "NES", "RBI Baseball [Gray Cart]", null },
                    { "612", "9639", null, "Racing", "NES", "RC Pro-AM II", null },
                    { "613", "34135", null, "Accessories", "NES", "ROB the Robot", null },
                    { "614", "9615", null, "Racing", "NES", "Race America", null },
                    { "615", "30824", null, "Action & Adventure", "NES", "Racermate Challenge II", null },
                    { "616", "12376", null, "Sports", "NES", "Racket Attack", null },
                    { "617", "12378", null, "Racing", "NES", "Rad Racer", null },
                    { "618", "12379", null, "Racing", "NES", "Rad Racer II", null },
                    { "619", "38037", null, "Racing", "NES", "Rad Racer [5 Screw]", null },
                    { "620", "30982", null, "Sports", "NES", "Rad Racket: Deluxe Tennis II", null },
                    { "621", "12380", null, "Action & Adventure", "NES", "Raid 2020", null },
                    { "622", "12381", null, "Action & Adventure", "NES", "Raid on Bungeling Bay", null },
                    { "611", "12375", null, "Racing", "NES", "RC Pro-AM", null },
                    { "623", "38025", null, "Action & Adventure", "NES", "Raid on Bungeling Bay [5 Screw]", null },
                    { "597", "12367", null, "Action & Adventure", "NES", "Pyramid", null },
                    { "595", "12365", null, "Puzzle", "NES", "Puzzle", null },
                    { "571", "12354", null, "Other", "NES", "Pictionary", null },
                    { "572", "12355", null, "Action & Adventure", "NES", "Pin-Bot", null },
                    { "573", "12005", null, "Arcade", "NES", "Pinball", null },
                    { "574", "12356", null, "Arcade", "NES", "Pinball Quest", null },
                    { "575", "37979", null, "Arcade", "NES", "Pinball [5 Screw]", null },
                    { "576", "12357", null, "Puzzle", "NES", "Pipe Dream", null },
                    { "577", "9558", null, "Action & Adventure", "NES", "Pirates", null },
                    { "578", "12358", null, "Action & Adventure", "NES", "Platoon", null },
                    { "579", "9566", null, "Football", "NES", "Play Action Football", null },
                    { "580", "12359", null, "Action & Adventure", "NES", "Popeye", null },
                    { "581", "37988", null, "Action & Adventure", "NES", "Popeye [5 Screw]", null },
                    { "596", "12366", null, "Puzzle", "NES", "Puzznic", null },
                    { "582", "9574", null, "Action & Adventure", "NES", "Power Blade", null },
                    { "584", "13715", null, "Controllers", "NES", "Power Glove", null },
                    { "585", "13761", null, "Controllers", "NES", "Power Pad", null },
                    { "586", "9577", null, "Fighting", "NES", "Power Punch II", null },
                    { "587", "12360", null, "Action & Adventure", "NES", "Predator", null },
                    { "588", "9584", null, "Action & Adventure", "NES", "Prince of Persia", null },
                    { "589", "12361", null, "Action & Adventure", "NES", "Princess Tomato in the Salad Kingdom", null },
                    { "590", "9592", null, "Sports", "NES", "Pro Sports Hockey", null },
                    { "591", "12362", null, "Wrestling", "NES", "Pro Wrestling", null },
                    { "592", "38001", null, "Wrestling", "NES", "Pro Wrestling [5 Screw]", null },
                    { "593", "12006", null, "Sports", "NES", "Punch-Out", null },
                    { "594", "12364", null, "Action & Adventure", "NES", "Puss N' Boots: Pero's Great Adventure", null },
                    { "583", "9575", null, "Action & Adventure", "NES", "Power Blade 2", null },
                    { "624", "12382", null, "Action & Adventure", "NES", "Rainbow Islands", null },
                    { "625", "12383", null, "Racing", "NES", "Rally Bike", null },
                    { "626", "12384", null, "Action & Adventure", "NES", "Rambo", null },
                    { "656", "38012", null, "Action & Adventure", "NES", "Rygar [5 Screw]", null },
                    { "657", "9697", null, "Action & Adventure", "NES", "SCAT Special Cybernetic Attack Team", null },
                    { "658", "12404", null, "Action & Adventure", "NES", "Secret Scout", null },
                    { "659", "12405", null, "Action & Adventure", "NES", "Section Z", null },
                    { "660", "38013", null, "Action & Adventure", "NES", "Section-Z [5 Screw]", null },
                    { "661", "12406", null, "Action & Adventure", "NES", "Seicross", null },
                    { "662", "13827", null, "Other", "NES", "Sesame Street 123", null },
                    { "663", "12408", null, "Other", "NES", "Sesame Street ABC", null },
                    { "664", "9720", null, "Other", "NES", "Sesame Street ABC and 123", null },
                    { "665", "12409", null, "Other", "NES", "Sesame Street Big Bird's Hide and Speak", null },
                    { "666", "9721", null, "Other", "NES", "Sesame Street Countdown", null },
                    { "655", "12403", null, "Action & Adventure", "NES", "Rygar", null },
                    { "667", "12410", null, "Action & Adventure", "NES", "Shadow of the Ninja", null },
                    { "669", "40395", null, "Systems", "NES", "Sharp Nintendo NES TV", null },
                    { "670", "9729", null, "Action & Adventure", "NES", "Shatterhand", null },
                    { "671", "12412", null, "Action & Adventure", "NES", "Shingen the Ruler", null },
                    { "672", "12413", null, "Action & Adventure", "NES", "Shinobi", null },
                    { "673", "12414", null, "Action & Adventure", "NES", "Shockwave", null },
                    { "674", "12415", null, "Other", "NES", "Shooting Range", null },
                    { "675", "12416", null, "Action & Adventure", "NES", "Short Order/Eggsplode", null },
                    { "676", "12417", null, "Sports", "NES", "Side Pocket", null },
                    { "677", "12418", null, "Action & Adventure", "NES", "Silent Assault", null },
                    { "678", "12419", null, "Action & Adventure", "NES", "Silent Service", null },
                    { "679", "12420", null, "Action & Adventure", "NES", "Silk Worm", null },
                    { "668", "12411", null, "Action & Adventure", "NES", "Shadowgate", null },
                    { "654", "38004", null, "Action & Adventure", "NES", "Rush'n Attack [5 Screw]", null },
                    { "653", "12402", null, "Action & Adventure", "NES", "Rush'n Attack", null },
                    { "652", "9687", null, "Basketball", "NES", "Roundball 2-on-2 Challenge", null },
                    { "627", "12385", null, "Action & Adventure", "NES", "Rampage", null },
                    { "628", "9624", null, "Racing", "NES", "Rampart", null },
                    { "629", "12387", null, "Action & Adventure", "NES", "Renegade", null },
                    { "630", "12388", null, "Action & Adventure", "NES", "Rescue the Embassy Mission", null },
                    { "631", "12389", null, "Action & Adventure", "NES", "Ring King", null },
                    { "632", "38026", null, "Sports", "NES", "Ring King [5 Screw]", null },
                    { "633", "12390", null, "Action & Adventure", "NES", "River City Ransom", null },
                    { "634", "12391", null, "Action & Adventure", "NES", "Road Runner", null },
                    { "635", "12392", null, "Action & Adventure", "NES", "RoadBlasters", null },
                    { "636", "9669", null, "Action & Adventure", "NES", "Robin Hood Prince of Thieves", null },
                    { "637", "12393", null, "Action & Adventure", "NES", "Robo Warrior", null },
                    { "638", "9671", null, "Action & Adventure", "NES", "RoboCop 2", null },
                    { "639", "12394", null, "Action & Adventure", "NES", "Robocop", null },
                    { "640", "9673", null, "Action & Adventure", "NES", "Robocop 3", null },
                    { "641", "16141", null, "Action & Adventure", "NES", "Robodemons", null },
                    { "642", "12395", null, "Action & Adventure", "NES", "Rock 'n Ball", null },
                    { "643", "12396", null, "Action & Adventure", "NES", "Rocket Ranger", null },
                    { "644", "9678", null, "Action & Adventure", "NES", "Rockin' Kats", null },
                    { "645", "9681", null, "Baseball", "NES", "Roger Clemens' MVP Baseball", null },
                    { "646", "12397", null, "Sports", "NES", "Roller Games", null },
                    { "647", "12398", null, "Action & Adventure", "NES", "Rollerball", null },
                    { "648", "9682", null, "Sports", "NES", "Rollerblade Racer", null },
                    { "649", "12399", null, "Action & Adventure", "NES", "Rolling Thunder", null },
                    { "650", "12400", null, "Strategy", "NES", "Romance of the Three Kingdoms", null },
                    { "651", "12401", null, "Strategy", "NES", "Romance of the Three Kingdoms II", null },
                    { "570", "12353", null, "Other", "NES", "Phantom Fighter", null },
                    { "569", "12352", null, "Action & Adventure", "NES", "Peter Pan and the Pirates", null },
                    { "568", "19452", null, "Action & Adventure", "NES", "Pesterminator", null },
                    { "567", "14932", null, "Action & Adventure", "NES", "Peek-a-Boo Poker", null },
                    { "486", "12332", null, "Racing", "NES", "Michael Andretti's World GP", null },
                    { "487", "9337", null, "Action & Adventure", "NES", "Mickey Mousecapade", null },
                    { "488", "9338", null, "Action & Adventure", "NES", "Mickey's Adventure in Numberland", null },
                    { "489", "9339", null, "Action & Adventure", "NES", "Mickey's Safari in Letterland", null },
                    { "490", "12333", null, "Racing", "NES", "Micro Machines", null },
                    { "491", "39523", null, "Racing", "NES", "Micro Machines [Aladdin]", null },
                    { "492", "12334", null, "Other", "NES", "Mig 29", null },
                    { "493", "9349", null, "Strategy", "NES", "Might and Magic", null },
                    { "494", "12002", null, "Action & Adventure", "NES", "Mighty Bomb Jack", null },
                    { "495", "38011", null, "Action & Adventure", "NES", "Mighty Bomb Jack [5 Screw]", null },
                    { "496", "9351", null, "Action & Adventure", "NES", "Mighty Final Fight", null },
                    { "485", "38511", null, "Action & Adventure", "NES", "Metroid [Yellow Label]", null },
                    { "497", "12001", null, "Sports", "NES", "Mike Tyson's Punch-Out", null },
                    { "499", "12336", null, "Arcade", "NES", "Millipede", null },
                    { "500", "12003", null, "Action & Adventure", "NES", "Milon's Secret Castle", null },
                    { "501", "12337", null, "Music", "NES", "Miracle Piano", null },
                    { "502", "50113", null, "Accessories", "NES", "Miracle Piano Keyboard", null },
                    { "503", "19303", null, "Other", "NES", "Mission Cobra", null },
                    { "504", "9358", null, "Action & Adventure", "NES", "Mission Impossible", null },
                    { "505", "9366", null, "Strategy", "NES", "Monopoly", null },
                    { "506", "12338", null, "Action & Adventure", "NES", "Monster Party", null },
                    { "507", "12339", null, "Racing", "NES", "Monster Truck Rally", null },
                    { "508", "12340", null, "Action & Adventure", "NES", "Monster in My Pocket", null },
                    { "509", "21116", null, "Action & Adventure", "NES", "Moon Ranger", null },
                    { "498", "39517", null, "Sports", "NES", "Mike Tyson's Punch-Out [5 Screw]", null },
                    { "484", "37991", null, "Action & Adventure", "NES", "Metroid [5 Screw]", null },
                    { "483", "9331", null, "Action & Adventure", "NES", "Metroid", null },
                    { "482", "12331", null, "Action & Adventure", "NES", "Metal Storm", null },
                    { "457", "12319", null, "Puzzle", "NES", "Marble Madness", null },
                    { "458", "12000", null, "Action & Adventure", "NES", "Mario Bros", null },
                    { "459", "37987", null, "Action & Adventure", "NES", "Mario Bros [5 Screw]", null },
                    { "460", "9287", null, "Action & Adventure", "NES", "Mario Is Missing", null },
                    { "461", "9289", null, "Action & Adventure", "NES", "Mario's Time Machine", null },
                    { "462", "12321", null, "Action & Adventure", "NES", "Master Chu and the Drunkard Hu", null },
                    { "463", "14925", null, "Action & Adventure", "NES", "Maxi 15", null },
                    { "464", "12322", null, "Action & Adventure", "NES", "Mechanized Attack", null },
                    { "465", "9314", null, "Action & Adventure", "NES", "Mega Man", null },
                    { "466", "37373", null, "Action & Adventure", "NES", "Mega Man 10", null },
                    { "467", "12323", null, "Action & Adventure", "NES", "Mega Man 2", null },
                    { "468", "53798", null, "Action & Adventure", "NES", "Mega Man 2 [30th Anniversary Edition]", null },
                    { "469", "9315", null, "Action & Adventure", "NES", "Mega Man 3", null },
                    { "470", "12324", null, "Action & Adventure", "NES", "Mega Man 4", null },
                    { "471", "9316", null, "Action & Adventure", "NES", "Mega Man 5", null },
                    { "472", "9317", null, "Action & Adventure", "NES", "Mega Man 6", null },
                    { "473", "34155", null, "Action & Adventure", "NES", "Mega Man 9 Press Kit", null },
                    { "474", "38045", null, "Action & Adventure", "NES", "Mega Man [5 Screw]", null },
                    { "475", "16294", null, "Other", "NES", "Megacom 76", null },
                    { "476", "12325", null, "Action & Adventure", "NES", "Menace Beach", null },
                    { "477", "12326", null, "Action & Adventure", "NES", "Mendel Palace", null },
                    { "478", "12327", null, "Action & Adventure", "NES", "Mermaids of Atlantis", null },
                    { "479", "12328", null, "Fighting", "NES", "Metal Fighter", null },
                    { "480", "12329", null, "Action & Adventure", "NES", "Metal Gear", null },
                    { "481", "12330", null, "Action & Adventure", "NES", "Metal Mech", null },
                    { "510", "9377", null, "Action & Adventure", "NES", "Motor City Patrol", null },
                    { "680", "12421", null, "Action & Adventure", "NES", "Silver Surfer", null },
                    { "511", "9382", null, "Action & Adventure", "NES", "Ms. Pac-Man (Namco)", null },
                    { "513", "12341", null, "Action & Adventure", "NES", "Muppet Adventure", null },
                    { "543", "38569", null, "Systems", "NES", "Nintendo NES Sports Set Console", null },
                    { "544", "14933", null, "Action & Adventure", "NES", "Nintendo World Championship", null },
                    { "545", "16173", null, "Action & Adventure", "NES", "Nintendo World Championship Gold", null },
                    { "546", "38640", null, "Other", "NES", "Nintendo World Championship [25th Anniversary]", null },
                    { "547", "34873", null, "Action & Adventure", "NES", "Nintendo World Championship [Reproduction]", null },
                    { "548", "9492", null, "Soccer", "NES", "Nintendo World Cup", null },
                    { "549", "9495", null, "Strategy", "NES", "Nobunaga's Ambition", null },
                    { "550", "13108", null, "Strategy", "NES", "Nobunaga's Ambition 2", null },
                    { "551", "12346", null, "Action & Adventure", "NES", "North and South", null },
                    { "552", "12347", null, "Action & Adventure", "NES", "ORB 3D", null },
                    { "553", "14281", null, "Action & Adventure", "NES", "Operation Secret Storm", null },
                    { "542", "40469", null, "Systems", "NES", "Nintendo NES Power Set Console", null },
                    { "554", "12348", null, "Action & Adventure", "NES", "Operation Wolf", null },
                    { "556", "9516", null, "Strategy", "NES", "Overlord", null },
                    { "557", "19390", null, "Strategy", "NES", "P'radikus Conflict", null },
                    { "558", "12350", null, "Action & Adventure", "NES", "POW Prisoners of War", null },
                    { "559", "9518", null, "Action & Adventure", "NES", "Pac-Man [Namco]", null },
                    { "560", "40508", null, "Arcade", "NES", "Pac-Man [Tengen Gray]", null },
                    { "561", "30882", null, "Arcade", "NES", "Pac-Man [Tengen]", null },
                    { "562", "12351", null, "Action & Adventure", "NES", "Pac-Mania", null },
                    { "563", "16126", null, "Other", "NES", "Palamedes", null },
                    { "564", "9523", null, "Action & Adventure", "NES", "Panic Restaurant", null },
                    { "565", "9528", null, "Racing", "NES", "Paperboy", null },
                    { "566", "9530", null, "Action & Adventure", "NES", "Paperboy 2", null },
                    { "555", "12349", null, "Puzzle", "NES", "Othello", null },
                    { "541", "39977", null, "Systems", "NES", "Nintendo NES Deluxe Set Console", null },
                    { "540", "13805", null, "Controllers", "NES", "Nintendo NES Controller", null },
                    { "539", "13743", null, "Systems", "NES", "Nintendo NES Console", null },
                    { "514", "9390", null, "Action & Adventure", "NES", "Mutant Virus", null },
                    { "515", "14929", null, "Action & Adventure", "NES", "Myriad 6-in-1", null },
                    { "516", "12342", null, "Action & Adventure", "NES", "Mystery Quest", null },
                    { "517", "12343", null, "Action & Adventure", "NES", "NARC", null },
                    { "518", "16388", null, "Controllers", "NES", "NES Advantage Controller", null },
                    { "519", "16389", null, "Accessories", "NES", "NES Four Score", null },
                    { "520", "21587", null, "Controllers", "NES", "NES Max Controller", null },
                    { "521", "9449", null, "Sports", "NES", "NES Open Tournament Golf", null },
                    { "522", "19364", null, "Accessories", "NES", "NES Satellite 4 Controller Port", null },
                    { "523", "9459", null, "Football", "NES", "NFL Football", null },
                    { "524", "21251", null, "Other", "NES", "NTF2 Test Cartridge", null },
                    { "525", "9483", null, "Racing", "NES", "Nigel Mansell's World Championship Racing", null },
                    { "526", "9487", null, "Action & Adventure", "NES", "Nightshade", null },
                    { "527", "12344", null, "Action & Adventure", "NES", "Ninja Crusaders", null },
                    { "528", "9488", null, "Action & Adventure", "NES", "Ninja Gaiden", null },
                    { "529", "12004", null, "Action & Adventure", "NES", "Ninja Gaiden II The Dark Sword of Chaos", null },
                    { "530", "9490", null, "Action & Adventure", "NES", "Ninja Gaiden III Ancient Ship of Doom", null },
                    { "531", "12345", null, "Action & Adventure", "NES", "Ninja Kid", null },
                    { "532", "37995", null, "Action & Adventure", "NES", "Ninja Kid [5 Screw]", null },
                    { "533", "19387", null, "Other", "NES", "Nintendo Campus Challenge 1991", null },
                    { "534", "34874", null, "Action & Adventure", "NES", "Nintendo Campus Challenge 1991 [Reproduction]", null },
                    { "535", "38568", null, "Systems", "NES", "Nintendo NES Action Set Console", null },
                    { "536", "38570", null, "Systems", "NES", "Nintendo NES Challenge Set Console", null },
                    { "537", "37130", null, "Systems", "NES", "Nintendo NES Classic Edition", null },
                    { "538", "37198", null, "Controllers", "NES", "Nintendo NES Classic Edition Controller", null },
                    { "512", "30883", null, "Arcade", "NES", "Ms. Pac-Man [Tengen]", null },
                    { "456", "13766", null, "Action & Adventure", "NES", "Mappy-Land", null },
                    { "681", "12422", null, "Extreme Sports", "NES", "Skate or Die", null },
                    { "683", "12424", null, "Extreme Sports", "NES", "Ski or Die", null },
                    { "826", "12499", null, "Sports", "NES", "Track and Field II", null },
                    { "827", "38005", null, "Sports", "NES", "Track and Field [5 Screw]", null },
                    { "828", "10064", null, "Action & Adventure", "NES", "Treasure Master", null },
                    { "829", "10068", null, "Action & Adventure", "NES", "Trog", null },
                    { "830", "12500", null, "Action & Adventure", "NES", "Trojan", null },
                    { "831", "38000", null, "Action & Adventure", "NES", "Trojan [5 Screw]", null },
                    { "832", "12501", null, "Action & Adventure", "NES", "Trolls on Treasure Island", null },
                    { "833", "12502", null, "Action & Adventure", "NES", "Twin Cobra", null },
                    { "834", "12503", null, "Action & Adventure", "NES", "Twin Eagle", null },
                    { "835", "54274", null, "Controllers", "NES", "UForce", null },
                    { "836", "12504", null, "RPG", "NES", "Ultima Exodus", null },
                    { "825", "12498", null, "Sports", "NES", "Track and Field", null },
                    { "837", "12505", null, "RPG", "NES", "Ultima Quest of the Avatar", null },
                    { "839", "10081", null, "Action & Adventure", "NES", "Ultimate Air Combat", null },
                    { "840", "12506", null, "Basketball", "NES", "Ultimate Basketball", null },
                    { "841", "12507", null, "Soccer", "NES", "Ultimate League Soccer", null },
                    { "842", "12481", null, "Action & Adventure", "NES", "Ultimate Stuntman", null },
                    { "843", "10090", null, "Strategy", "NES", "Uncharted Waters", null },
                    { "844", "10091", null, "Action & Adventure", "NES", "Uninvited", null },
                    { "845", "12012", null, "Action & Adventure", "NES", "Urban Champion", null },
                    { "846", "37989", null, "Action & Adventure", "NES", "Urban Champion [5 Screw]", null },
                    { "847", "12508", null, "Other", "NES", "Vegas Dream", null },
                    { "848", "12509", null, "Sports", "NES", "Venice Beach Volleyball", null },
                    { "849", "12510", null, "Action & Adventure", "NES", "Vice Project Doom", null },
                    { "838", "10080", null, "RPG", "NES", "Ultima Warriors of Destiny", null },
                    { "850", "10105", null, "Other", "NES", "Videomation", null },
                    { "824", "10056", null, "Action & Adventure", "NES", "Toxic Crusaders", null },
                    { "822", "12483", null, "Action & Adventure", "NES", "Town & Country II: Thrilla's Surfari", null },
                    { "798", "12484", null, "Action & Adventure", "NES", "Thunder and Lightning", null },
                    { "799", "12485", null, "Action & Adventure", "NES", "Thunderbirds", null },
                    { "800", "12486", null, "Action & Adventure", "NES", "Thundercade", null },
                    { "801", "12487", null, "Other", "NES", "Tiger-Heli", null },
                    { "802", "38033", null, "Action & Adventure", "NES", "Tiger-Heli [5 Screw]", null },
                    { "803", "12488", null, "Puzzle", "NES", "Tiles of Fate", null },
                    { "804", "12489", null, "Action & Adventure", "NES", "Time Lord", null },
                    { "805", "10020", null, "RPG", "NES", "Times of Lore", null },
                    { "806", "10021", null, "Action & Adventure", "NES", "Tiny Toon Adventures", null },
                    { "807", "10022", null, "Action & Adventure", "NES", "Tiny Toon Adventures 2 Trouble in Wackyland", null },
                    { "808", "10024", null, "Action & Adventure", "NES", "Tiny Toon Adventures Cartoon Workshop", null },
                    { "823", "12461", null, "Sports", "NES", "Town & Country Surf Designs: Wood and Water Rage", null },
                    { "809", "12490", null, "Action & Adventure", "NES", "To the Earth", null },
                    { "811", "10035", null, "Action & Adventure", "NES", "Tom and Jerry", null },
                    { "812", "12492", null, "Action & Adventure", "NES", "Tombs and Treasure", null },
                    { "813", "12493", null, "Action & Adventure", "NES", "Toobin'", null },
                    { "814", "12494", null, "Action & Adventure", "NES", "Top Gun", null },
                    { "815", "10052", null, "Other", "NES", "Top Gun The Second Mission", null },
                    { "816", "38044", null, "Action & Adventure", "NES", "Top Gun [5 Screw]", null },
                    { "817", "13883", null, "Systems", "NES", "Top Loading Nintendo NES Console", null },
                    { "818", "12495", null, "Sports", "NES", "Top Players Tennis", null },
                    { "819", "10053", null, "Action & Adventure", "NES", "Total Recall", null },
                    { "820", "12496", null, "Racing", "NES", "Totally Rad", null },
                    { "821", "12497", null, "Football", "NES", "Touchdown Fever", null },
                    { "810", "12491", null, "Action & Adventure", "NES", "Toki", null },
                    { "851", "12511", null, "Action & Adventure", "NES", "Vindicators", null },
                    { "852", "12013", null, "Sports", "NES", "Volleyball", null },
                    { "853", "38003", null, "Sports", "NES", "Volleyball [5 Screw]", null },
                    { "883", "12528", null, "RPG", "NES", "Wizards and Warriors", null },
                    { "884", "10167", null, "Action & Adventure", "NES", "Wizards and Warriors III Kuros Visions of Power", null },
                    { "885", "38046", null, "Action & Adventure", "NES", "Wizards and Warriors [5 Screw]", null },
                    { "886", "10169", null, "Action & Adventure", "NES", "Wolverine", null },
                    { "887", "10172", null, "Sports", "NES", "World Champ", null },
                    { "888", "12530", null, "Sports", "NES", "World Class Track Meet", null },
                    { "889", "12532", null, "Sports", "NES", "World Games", null },
                    { "890", "12533", null, "Action & Adventure", "NES", "Wrath of the Black Manta", null },
                    { "891", "12014", null, "Action & Adventure", "NES", "Wrecking Crew", null },
                    { "892", "37975", null, "Action & Adventure", "NES", "Wrecking Crew [5 Screw]", null },
                    { "893", "10208", null, "Action & Adventure", "NES", "Wurm Journey to the Center of the Earth", null },
                    { "882", "19592", null, "RPG", "NES", "Wizardry: Proving Grounds of the Mad Overlord", null },
                    { "894", "12534", null, "Action & Adventure", "NES", "Xenophobe", null },
                    { "896", "12535", null, "Action & Adventure", "NES", "Xexyz", null },
                    { "897", "12536", null, "Action & Adventure", "NES", "Yo Noid", null }
                });

            migrationBuilder.InsertData(
                table: "Games",
                columns: new[] { "Id", "ApiGameId", "CoverURL", "Genre", "SystemId", "Title", "Upc" },
                values: new object[,]
                {
                    { "898", "10228", null, "Puzzle", "NES", "Yoshi", null },
                    { "899", "10229", null, "Puzzle", "NES", "Yoshi's Cookie", null },
                    { "900", "10230", null, "Action & Adventure", "NES", "Young Indiana Jones Chronicles", null },
                    { "901", "12016", null, "Action & Adventure", "NES", "Zanac", null },
                    { "902", "38038", null, "Action & Adventure", "NES", "Zanac [5 Screw]", null },
                    { "903", "13716", null, "Controllers", "NES", "Zapper Light Gun", null },
                    { "904", "10234", null, "RPG", "NES", "Zelda II The Adventure of Link", null },
                    { "905", "38510", null, "Action & Adventure", "NES", "Zelda II The Adventure of Link [Gray Cart]", null },
                    { "906", "20786", null, "Other", "NES", "Zelda Test Cartridge", null },
                    { "895", "12015", null, "Action & Adventure", "NES", "Xevious", null },
                    { "881", "10166", null, "RPG", "NES", "Wizardry: Knight of Diamonds Second Scenario", null },
                    { "880", "38034", null, "Sports", "NES", "Winter Games [5 Screw]", null },
                    { "879", "12525", null, "Sports", "NES", "Winter Games", null },
                    { "854", "12512", null, "Wrestling", "NES", "WCW World Championship Wrestling", null },
                    { "855", "10214", null, "Wrestling", "NES", "WWF King of the Ring", null },
                    { "856", "10221", null, "Wrestling", "NES", "WWF Wrestlemania", null },
                    { "857", "13833", null, "Wrestling", "NES", "WWF Wrestlemania Challenge", null },
                    { "858", "10218", null, "Wrestling", "NES", "WWF Wrestlemania Steel Cage Challenge", null },
                    { "859", "10132", null, "Racing", "NES", "Wacky Races", null },
                    { "860", "10133", null, "Strategy", "NES", "Wall Street Kid", null },
                    { "861", "12513", null, "Action & Adventure", "NES", "Wally Bear and the No Gang", null },
                    { "862", "10138", null, "Puzzle", "NES", "Wario's Woods", null },
                    { "863", "12514", null, "Sports", "NES", "Wayne Gretzky Hockey", null },
                    { "864", "10146", null, "Action & Adventure", "NES", "Wayne's World", null },
                    { "865", "12515", null, "Action & Adventure", "NES", "Werewolf", null },
                    { "866", "12517", null, "Other", "NES", "Wheel of Fortune", null },
                    { "867", "12516", null, "Other", "NES", "Wheel of Fortune Family Edition", null },
                    { "868", "10149", null, "Other", "NES", "Wheel of Fortune Featuring Vanna White", null },
                    { "869", "12518", null, "Other", "NES", "Wheel of Fortune Junior Edition", null },
                    { "870", "10152", null, "Action & Adventure", "NES", "Where in Time is Carmen Sandiego", null },
                    { "871", "12519", null, "Other", "NES", "Where's Waldo", null },
                    { "872", "12520", null, "Action & Adventure", "NES", "Who Framed Roger Rabbit", null },
                    { "873", "12521", null, "Action & Adventure", "NES", "Whomp 'Em", null },
                    { "874", "10154", null, "Action & Adventure", "NES", "Widget", null },
                    { "875", "12522", null, "Other", "NES", "Wild Gunman", null },
                    { "876", "37974", null, "Action & Adventure", "NES", "Wild Gunman [5 Screw]", null },
                    { "877", "12523", null, "Action & Adventure", "NES", "Willow", null },
                    { "878", "12524", null, "Other", "NES", "Win Lose or Draw", null },
                    { "797", "10096", null, "Action & Adventure", "NES", "The Untouchables", null },
                    { "796", "12482", null, "Action & Adventure", "NES", "The Uncanny X-Men", null },
                    { "795", "12480", null, "Action & Adventure", "NES", "The Three Stooges", null },
                    { "794", "9751", null, "Action & Adventure", "NES", "The Simpsons Bartman Meets Radioactive Man", null },
                    { "713", "9839", null, "Action & Adventure", "NES", "Stanley The Search for Dr Livingston", null },
                    { "714", "12439", null, "Action & Adventure", "NES", "Star Force", null },
                    { "715", "38042", null, "Action & Adventure", "NES", "Star Force [5 Screw]", null },
                    { "716", "12009", null, "Other", "NES", "Star Soldier", null },
                    { "717", "9842", null, "Action & Adventure", "NES", "Star Trek 25th Anniversary", null },
                    { "718", "9847", null, "Action & Adventure", "NES", "Star Trek The Next Generation", null },
                    { "719", "9848", null, "Strategy", "NES", "Star Tropics", null },
                    { "720", "10238", null, "RPG", "NES", "Star Tropics II: Zoda's Revenge", null },
                    { "721", "12440", null, "Action & Adventure", "NES", "Star Voyager", null },
                    { "722", "38031", null, "Action & Adventure", "NES", "Star Voyager [5 Screw]", null },
                    { "723", "9849", null, "Action & Adventure", "NES", "Star Wars", null },
                    { "712", "16127", null, "Other", "NES", "Stack Up", null },
                    { "724", "9857", null, "Action & Adventure", "NES", "Star Wars The Empire Strikes Back", null },
                    { "726", "18720", null, "Other", "NES", "Stealth", null },
                    { "727", "12443", null, "Action & Adventure", "NES", "Stinger", null },
                    { "728", "12444", null, "Action & Adventure", "NES", "Street Cop", null },
                    { "729", "12445", null, "Fighting", "NES", "Street Fighter 2010 the Final Fight", null },
                    { "730", "12446", null, "Action & Adventure", "NES", "Strider", null },
                    { "731", "12447", null, "Action & Adventure", "NES", "Stunt Kids", null },
                    { "732", "19476", null, "Action & Adventure", "NES", "Sunday Funday", null },
                    { "733", "9883", null, "Other", "NES", "Super C", null },
                    { "734", "12448", null, "Racing", "NES", "Super Cars", null },
                    { "735", "12449", null, "Sports", "NES", "Super Dodge Ball", null },
                    { "736", "12450", null, "Sports", "NES", "Super Glove Ball", null },
                    { "725", "12441", null, "Action & Adventure", "NES", "Starship Hector", null },
                    { "711", "12438", null, "Action & Adventure", "NES", "Sqoon", null },
                    { "710", "9832", null, "Action & Adventure", "NES", "Spy vs. Spy", null },
                    { "709", "38029", null, "Racing", "NES", "Spy Hunter [5 Screw]", null },
                    { "684", "12425", null, "Action & Adventure", "NES", "Skull and Crossbones", null },
                    { "685", "12426", null, "Action & Adventure", "NES", "Sky Kid", null },
                    { "686", "38027", null, "Action & Adventure", "NES", "Sky Kid [5 Screw]", null },
                    { "687", "12427", null, "Action & Adventure", "NES", "Sky Shark", null },
                    { "688", "12428", null, "Sports", "NES", "Slalom", null },
                    { "689", "38019", null, "Sports", "NES", "Slalom [5 Screw]", null },
                    { "690", "9764", null, "Action & Adventure", "NES", "Smash TV", null },
                    { "691", "12429", null, "Action & Adventure", "NES", "Snake Rattle n Roll", null },
                    { "692", "9765", null, "Action & Adventure", "NES", "Snake's Revenge", null },
                    { "693", "12430", null, "Sports", "NES", "Snoopy Silly Sports", null },
                    { "694", "9768", null, "Puzzle", "NES", "Snow Brothers", null },
                    { "695", "12007", null, "Soccer", "NES", "Soccer", null },
                    { "696", "38002", null, "Soccer", "NES", "Soccer [5 Screw]", null },
                    { "697", "12431", null, "Action & Adventure", "NES", "Solar Jetman", null },
                    { "698", "12432", null, "Other", "NES", "Solitaire", null },
                    { "699", "12008", null, "Action & Adventure", "NES", "Solomon's Key", null },
                    { "700", "38014", null, "Action & Adventure", "NES", "Solomon's Key [5 Screw]", null },
                    { "701", "9776", null, "Puzzle", "NES", "Solstice", null },
                    { "702", "9803", null, "Other", "NES", "Space Shuttle", null },
                    { "703", "12434", null, "Action & Adventure", "NES", "Spelunker", null },
                    { "704", "38028", null, "Action & Adventure", "NES", "Spelunker [5 Screw]", null },
                    { "705", "10594", null, "Action & Adventure", "NES", "Spiderman Return of the Sinister Six", null },
                    { "706", "12436", null, "Action & Adventure", "NES", "Spiritual Warfare", null },
                    { "707", "9830", null, "Strategy", "NES", "Spot", null },
                    { "708", "12437", null, "Action & Adventure", "NES", "Spy Hunter", null },
                    { "737", "9889", null, "Action & Adventure", "NES", "Super Mario Bros", null },
                    { "682", "12423", null, "Extreme Sports", "NES", "Skate or Die 2", null },
                    { "738", "12010", null, "Action & Adventure", "NES", "Super Mario Bros 2", null },
                    { "740", "12452", null, "Action & Adventure", "NES", "Super Mario Bros Duck Hunt World Class Track Meet", null },
                    { "770", "9942", null, "Action & Adventure", "NES", "Teenage Mutant Ninja Turtles III The Manhattan Project", null },
                    { "771", "9944", null, "Fighting", "NES", "Teenage Mutant Ninja Turtles Tournament Fighters", null },
                    { "772", "12011", null, "Sports", "NES", "Tennis", null },
                    { "773", "37982", null, "Sports", "NES", "Tennis [5 Screw]", null },
                    { "774", "9951", null, "Action & Adventure", "NES", "Terminator", null },
                    { "775", "9953", null, "Action & Adventure", "NES", "Terminator 2 Judgment Day", null },
                    { "776", "12469", null, "Action & Adventure", "NES", "Terra Cresta", null },
                    { "777", "9964", null, "Puzzle", "NES", "Tetris", null },
                    { "778", "9966", null, "Puzzle", "NES", "Tetris 2", null },
                    { "779", "12595", null, "Puzzle", "NES", "Tetris [Tengen]", null },
                    { "780", "8471", null, "Action & Adventure", "NES", "The Adventures of Rocky and Bullwinkle and Friends", null },
                    { "769", "12468", null, "Action & Adventure", "NES", "Teenage Mutant Ninja Turtles II", null },
                    { "781", "12471", null, "Action & Adventure", "NES", "The Goonies II", null },
                    { "783", "12472", null, "Action & Adventure", "NES", "The Guardian Legend", null },
                    { "784", "9990", null, "Action & Adventure", "NES", "The Jungle Book", null },
                    { "785", "12474", null, "Action & Adventure", "NES", "The Karate Kid", null },
                    { "786", "12475", null, "Action & Adventure", "NES", "The Last Ninja", null },
                    { "787", "12477", null, "Action & Adventure", "NES", "The Mafat Conspiracy", null },
                    { "788", "12478", null, "Action & Adventure", "NES", "The Magic of Scheherazade", null },
                    { "789", "9997", null, "Action & Adventure", "NES", "The Punisher", null },
                    { "790", "9648", null, "Action & Adventure", "NES", "The Ren and Stimpy Show Buckeroos", null },
                    { "791", "9677", null, "Action & Adventure", "NES", "The Rocketeer", null },
                    { "792", "12479", null, "Action & Adventure", "NES", "The Simpsons Bart vs the Space Mutants", null },
                    { "793", "12197", null, "Action & Adventure", "NES", "The Simpsons Bart vs the World", null },
                    { "782", "38040", null, "Action & Adventure", "NES", "The Goonies II [5 Screw]", null },
                    { "768", "9941", null, "Action & Adventure", "NES", "Teenage Mutant Ninja Turtles", null },
                    { "767", "9938", null, "Wrestling", "NES", "Tecmo World Wrestling", null },
                    { "766", "9934", null, "Football", "NES", "Tecmo Super Bowl", null },
                    { "741", "37981", null, "Action & Adventure", "NES", "Super Mario Bros [5 Screw]", null },
                    { "742", "12451", null, "Action & Adventure", "NES", "Super Mario Bros and Duck Hunt", null },
                    { "743", "12453", null, "Racing", "NES", "Super Off Road", null },
                    { "744", "12454", null, "Action & Adventure", "NES", "Super Pitfall", null },
                    { "745", "38043", null, "Action & Adventure", "NES", "Super Pitfall [5 Screw]", null },
                    { "746", "9898", null, "Sports", "NES", "Super Spike Volleyball", null },
                    { "747", "12455", null, "Sports", "NES", "Super Spike Volleyball and World Cup Soccer", null },
                    { "748", "12456", null, "Racing", "NES", "Super Sprint", null },
                    { "749", "9899", null, "Racing", "NES", "Super Spy Hunter", null },
                    { "750", "12457", null, "Sports", "NES", "Super Team Games", null },
                    { "751", "12458", null, "Action & Adventure", "NES", "Superman", null },
                    { "752", "9913", null, "Action & Adventure", "NES", "Swamp Thing", null },
                    { "753", "19306", null, "Action & Adventure", "NES", "Sword Master", null },
                    { "754", "12459", null, "Action & Adventure", "NES", "Swords and Serpents", null },
                    { "755", "12462", null, "Action & Adventure", "NES", "Taboo the Sixth Sense", null },
                    { "756", "12463", null, "Wrestling", "NES", "Tag Team Wrestling", null },
                    { "757", "37994", null, "Wrestling", "NES", "Tag Team Wrestling [5 Screw]", null },
                    { "758", "30846", null, "Action & Adventure", "NES", "Tagin' Dragon", null },
                    { "759", "12162", null, "Action & Adventure", "NES", "TaleSpin", null },
                    { "760", "12465", null, "Other", "NES", "Talking Super Jeopardy", null },
                    { "761", "12466", null, "Action & Adventure", "NES", "Target Renegade", null },
                    { "762", "12467", null, "Baseball", "NES", "Tecmo Baseball", null },
                    { "763", "9929", null, "Football", "NES", "Tecmo Bowl", null },
                    { "764", "9930", null, "Soccer", "NES", "Tecmo Cup Soccer", null },
                    { "765", "9931", null, "Basketball", "NES", "Tecmo NBA Basketball", null },
                    { "739", "9891", null, "Action & Adventure", "NES", "Super Mario Bros 3", null },
                    { "455", "12317", null, "Action & Adventure", "NES", "Maniac Mansion", null },
                    { "454", "12316", null, "Baseball", "NES", "Major League Baseball", null },
                    { "453", "12315", null, "Action & Adventure", "NES", "Magmax", null },
                    { "144", "38007", null, "Action & Adventure", "NES", "Castlevania [5 Screw]", null },
                    { "145", "12126", null, "Party", "NES", "Caveman Games", null },
                    { "146", "16130", null, "Action & Adventure", "NES", "Challenge of the Dragon", null },
                    { "147", "8713", null, "Sports", "NES", "Championship Bowling", null },
                    { "148", "8714", null, "Sports", "NES", "Championship Pool", null },
                    { "149", "14927", null, "Action & Adventure", "NES", "Cheetahmen II", null },
                    { "150", "8722", null, "Strategy", "NES", "Chessmaster", null },
                    { "151", "8729", null, "Action & Adventure", "NES", "Chiller", null },
                    { "152", "12127", null, "Action & Adventure", "NES", "Chip and Dale Rescue Rangers", null },
                    { "153", "8730", null, "Action & Adventure", "NES", "Chip and Dale Rescue Rangers 2", null },
                    { "154", "12128", null, "Action & Adventure", "NES", "Chubby Cherub", null },
                    { "143", "8706", null, "Action & Adventure", "NES", "Castlevania III Dracula's Curse", null },
                    { "155", "12129", null, "Action & Adventure", "NES", "Circus Caper", null },
                    { "157", "12131", null, "Action & Adventure", "NES", "Clash at Demonhead", null },
                    { "158", "12132", null, "Action & Adventure", "NES", "Classic Concentration", null },
                    { "159", "38378", null, "Accessories", "NES", "Cleaning Kit", null },
                    { "160", "8738", null, "Action & Adventure", "NES", "Cliffhanger", null },
                    { "161", "12133", null, "Action & Adventure", "NES", "Clu Clu Land", null },
                    { "162", "12134", null, "Action & Adventure", "NES", "Cobra Command", null },
                    { "163", "8743", null, "Action & Adventure", "NES", "Cobra Triangle", null },
                    { "164", "8747", null, "Action & Adventure", "NES", "Code Name Viper", null },
                    { "165", "8753", null, "Other", "NES", "Color A Dinosaur", null },
                    { "166", "12135", null, "Action & Adventure", "NES", "Commando", null },
                    { "167", "37997", null, "Other", "NES", "Commando [5 Screw]", null },
                    { "156", "12130", null, "Action & Adventure", "NES", "City Connection", null },
                    { "168", "12136", null, "Action & Adventure", "NES", "Conan the Mysteries of Time", null },
                    { "142", "11984", null, "Action & Adventure", "NES", "Castlevania II Simon's Quest", null },
                    { "140", "12124", null, "Action & Adventure", "NES", "Castlequest", null },
                    { "116", "38039", null, "Action & Adventure", "NES", "Breakthru [5 Screw]", null },
                    { "117", "14930", null, "Action & Adventure", "NES", "Bubble Bath Babes", null },
                    { "118", "11983", null, "Action & Adventure", "NES", "Bubble Bobble", null },
                    { "119", "8654", null, "Action & Adventure", "NES", "Bubble Bobble Part 2", null },
                    { "120", "8658", null, "Action & Adventure", "NES", "Bucky O'Hare", null },
                    { "121", "8661", null, "Action & Adventure", "NES", "Bugs Bunny Birthday Blowout", null },
                    { "122", "8662", null, "Action & Adventure", "NES", "Bugs Bunny Crazy Castle", null },
                    { "123", "12114", null, "Action & Adventure", "NES", "Bump 'n' Jump", null },
                    { "124", "12115", null, "Fighting", "NES", "Burai Fighter", null },
                    { "125", "38006", null, "Action & Adventure", "NES", "BurgerTime [5 Screw]", null },
                    { "126", "12116", null, "Puzzle", "NES", "Burgertime", null },
                    { "141", "8704", null, "Action & Adventure", "NES", "Castlevania", null },
                    { "127", "12117", null, "Action & Adventure", "NES", "Cabal", null },
                    { "129", "12118", null, "Sports", "NES", "California Games", null },
                    { "130", "8687", null, "Action & Adventure", "NES", "California Raisins The Great Escape [Reproduction]", null },
                    { "131", "14928", null, "Action & Adventure", "NES", "Caltron 6-in-1", null },
                    { "132", "8695", null, "Action & Adventure", "NES", "Captain America and the Avengers", null },
                    { "133", "8696", null, "Action & Adventure", "NES", "Captain Planet and the Planeteers", null },
                    { "134", "12120", null, "Action & Adventure", "NES", "Captain Skyhawk", null },
                    { "135", "12121", null, "Other", "NES", "Casino Kid", null },
                    { "136", "8701", null, "Other", "NES", "Casino Kid II", null },
                    { "137", "8702", null, "Action & Adventure", "NES", "Castelian", null },
                    { "138", "12122", null, "Action & Adventure", "NES", "Castle of Deceit", null },
                    { "139", "12123", null, "Action & Adventure", "NES", "Castle of Dragon", null },
                    { "128", "8683", null, "Sports", "NES", "Caesar's Palace", null },
                    { "169", "12137", null, "Action & Adventure", "NES", "Conflict", null },
                    { "170", "12138", null, "Action & Adventure", "NES", "Conquest of the Crystal Palace", null },
                    { "171", "12139", null, "Action & Adventure", "NES", "Contra", null },
                    { "201", "12157", null, "Action & Adventure", "NES", "Dick Tracy", null },
                    { "202", "8841", null, "Action & Adventure", "NES", "Die Hard", null },
                    { "203", "12159", null, "Action & Adventure", "NES", "Dig Dug II: Trouble in Paradise", null },
                    { "204", "12160", null, "Action & Adventure", "NES", "Digger T Rock", null },
                    { "205", "12161", null, "Action & Adventure", "NES", "Dirty Harry", null },
                    { "206", "39508", null, "Puzzle", "NES", "Dizzy the Adventurer", null },
                    { "207", "21555", null, "Controllers", "NES", "Dogbone Controller", null },
                    { "208", "11985", null, "Action & Adventure", "NES", "Donkey Kong", null },
                    { "209", "12163", null, "Action & Adventure", "NES", "Donkey Kong 3", null },
                    { "210", "37986", null, "Action & Adventure", "NES", "Donkey Kong 3 [5 Screw]", null },
                    { "211", "12164", null, "Action & Adventure", "NES", "Donkey Kong Classics", null },
                    { "200", "12156", null, "Action & Adventure", "NES", "Destiny of an Emperor", null },
                    { "212", "11986", null, "Action & Adventure", "NES", "Donkey Kong Jr", null },
                    { "214", "37968", null, "Action & Adventure", "NES", "Donkey Kong Jr Math [5 Screw]", null },
                    { "215", "37985", null, "Action & Adventure", "NES", "Donkey Kong Jr [5 Screw]", null },
                    { "216", "37984", null, "Action & Adventure", "NES", "Donkey Kong [5 Screw]", null },
                    { "217", "12167", null, "Action & Adventure", "NES", "Double Dare", null },
                    { "218", "12207", null, "Action & Adventure", "NES", "Double Dragon", null },
                    { "219", "12208", null, "Action & Adventure", "NES", "Double Dragon II", null },
                    { "220", "12209", null, "Action & Adventure", "NES", "Double Dragon III", null },
                    { "221", "11988", null, "Basketball", "NES", "Double Dribble", null },
                    { "222", "38023", null, "Basketball", "NES", "Double Dribble [5 Screw]", null },
                    { "223", "12210", null, "Action & Adventure", "NES", "Double Strike", null },
                    { "224", "12211", null, "Action & Adventure", "NES", "Dr Chaos", null },
                    { "213", "11987", null, "Other", "NES", "Donkey Kong Jr Math", null },
                    { "199", "12155", null, "Other", "NES", "Destination Earthstar", null },
                    { "198", "12154", null, "Action & Adventure", "NES", "Desert Commander", null },
                    { "197", "12153", null, "Action & Adventure", "NES", "Demon Sword", null },
                    { "172", "12140", null, "Action & Adventure", "NES", "Contra Force", null },
                    { "173", "37258", null, "Other", "NES", "Control Deck Test Cartridge", null },
                    { "174", "8764", null, "Action & Adventure", "NES", "Cool World", null },
                    { "175", "12142", null, "Action & Adventure", "NES", "Cowboy Kid", null },
                    { "176", "12143", null, "Action & Adventure", "NES", "Crash 'n' the Boys: Street Challenge", null },
                    { "177", "8786", null, "Action & Adventure", "NES", "Crystal Mines", null },
                    { "178", "12144", null, "Action & Adventure", "NES", "Crystalis", null },
                    { "179", "8794", null, "Sports", "NES", "Cyberball", null },
                    { "180", "8796", null, "Action & Adventure", "NES", "Cybernoid The Fighting Machine", null },
                    { "181", "12145", null, "Sports", "NES", "Cyberstadium Series Base Wars", null },
                    { "182", "8801", null, "Other", "NES", "Dance Aerobics", null },
                    { "183", "8804", null, "Racing", "NES", "Danny Sullivan's Indy Heat", null },
                    { "184", "8808", null, "Action & Adventure", "NES", "Darkman", null },
                    { "185", "8810", null, "Action & Adventure", "NES", "Darkwing Duck", null },
                    { "186", "12146", null, "Action & Adventure", "NES", "Dash Galaxy in the Alien Asylum", null },
                    { "187", "8817", null, "Action & Adventure", "NES", "Day Dreamin' Davey", null },
                    { "188", "8818", null, "Racing", "NES", "Days Of Thunder", null },
                    { "189", "12147", null, "Action & Adventure", "NES", "Deadly Towers", null },
                    { "190", "38022", null, "Action & Adventure", "NES", "Deadly Towers [5 Screw]", null },
                    { "191", "12148", null, "Racing", "NES", "Death Race", null },
                    { "192", "12149", null, "Action & Adventure", "NES", "Deathbots", null },
                    { "193", "12150", null, "Action & Adventure", "NES", "Defender II", null },
                    { "194", "12151", null, "Action & Adventure", "NES", "Defender of the Crown", null },
                    { "195", "8836", null, "Action & Adventure", "NES", "Defenders of Dynatron City", null },
                    { "196", "12152", null, "Action & Adventure", "NES", "Deja Vu", null },
                    { "115", "12113", null, "Puzzle", "NES", "BreakThru", null },
                    { "114", "8645", null, "Sports", "NES", "Break Time The National Pool Tour", null },
                    { "113", "8643", null, "Action & Adventure", "NES", "Bram Stoker's Dracula", null },
                    { "112", "12112", null, "Action & Adventure", "NES", "Boulder Dash", null },
                    { "31 ", "8472", null, "Action & Adventure", "NES", "Adventures of Tom Sawyer", null },
                    { "32 ", "12177", null, "Other", "NES", "After Burner", null },
                    { "33 ", "8488", null, "Other", "NES", "Air Fortress", null },
                    { "34 ", "12178", null, "Action & Adventure", "NES", "Airwolf", null },
                    { "35 ", "8491", null, "Racing", "NES", "Al Unser Turbo Racing", null },
                    { "36 ", "39509", null, "Accessories", "NES", "Aladdin Deck Enhancer", null },
                    { "37 ", "8493", null, "Action & Adventure", "NES", "Alfred Chicken", null },
                    { "38 ", "8495", null, "Action & Adventure", "NES", "Alien 3", null },
                    { "39 ", "12179", null, "Action & Adventure", "NES", "Alien Syndrome", null },
                    { "40 ", "12180", null, "Basketball", "NES", "All-Pro Basketball", null },
                    { "41 ", "12181", null, "Action & Adventure", "NES", "Alpha Mission", null },
                    { "30 ", "12377", null, "Action & Adventure", "NES", "Adventures of Rad Gravity", null },
                    { "42 ", "38035", null, "Action & Adventure", "NES", "Alpha Mission [5 Screw]", null },
                    { "44 ", "8507", null, "Sports", "NES", "American Gladiators", null },
                    { "45 ", "12184", null, "Action & Adventure", "NES", "Anticipation", null },
                    { "46 ", "12185", null, "Basketball", "NES", "Arch Rivals", null },
                    { "47 ", "12186", null, "Action & Adventure", "NES", "Archon", null },
                    { "48 ", "8527", null, "Arcade", "NES", "Arkanoid", null },
                    { "49 ", "38015", null, "Action & Adventure", "NES", "Arkanoid [5 Screw]", null },
                    { "50 ", "37957", null, "Arcade", "NES", "Arkanoid [Controller Bundle]", null },
                    { "51 ", "16264", null, "Action & Adventure", "NES", "Arkista's Ring", null },
                    { "52 ", "8538", null, "Action & Adventure", "NES", "Astyanax", null },
                    { "53 ", "12187", null, "Action & Adventure", "NES", "Athena", null },
                    { "54 ", "38016", null, "Action & Adventure", "NES", "Athena [5 Screw]", null },
                    { "43 ", "12183", null, "Action & Adventure", "NES", "Amagon", null },
                    { "29 ", "8469", null, "Puzzle", "NES", "Adventures of Lolo 3", null },
                    { "28 ", "11980", null, "Action & Adventure", "NES", "Adventures of Lolo 2", null },
                    { "27 ", "11979", null, "Action & Adventure", "NES", "Adventures of Lolo", null },
                    { "2  ", "37965", null, "Football", "NES", "10-Yard Fight [5 Screw]", null },
                    { "3  ", "12169", null, "Other", "NES", "1942", null }
                });

            migrationBuilder.InsertData(
                table: "Games",
                columns: new[] { "Id", "ApiGameId", "CoverURL", "Genre", "SystemId", "Title", "Upc" },
                values: new object[,]
                {
                    { "4  ", "37996", null, "Other", "NES", "1942 [5 Screw]", null },
                    { "5  ", "12170", null, "Other", "NES", "1943: The Battle of Midway", null },
                    { "6  ", "8445", null, "Action & Adventure", "NES", "3D WorldRunner", null },
                    { "7  ", "38021", null, "Action & Adventure", "NES", "3D WorldRunner [5 Screw]", null },
                    { "8  ", "12171", null, "Sports", "NES", "720", null },
                    { "9  ", "12172", null, "Action & Adventure", "NES", "8 Eyes", null },
                    { "10 ", "12173", null, "Action & Adventure", "NES", "A Boy and His Blob Trouble on Blobolonia", null },
                    { "11 ", "12174", null, "Action & Adventure", "NES", "A Nightmare on Elm Street", null },
                    { "12 ", "8451", null, "Action & Adventure", "NES", "Abadox", null },
                    { "13 ", "8453", null, "Action & Adventure", "NES", "Action 52", null },
                    { "14 ", "8455", null, "Action & Adventure", "NES", "Addams Family", null },
                    { "15 ", "8456", null, "Action & Adventure", "NES", "Addams Family Pugsley's Scavenger Hunt", null },
                    { "16 ", "8458", null, "Strategy", "NES", "Advanced Dungeons & Dragons Dragon Strike", null },
                    { "17 ", "8459", null, "Strategy", "NES", "Advanced Dungeons & Dragons Heroes of the Lance", null },
                    { "18 ", "8460", null, "Strategy", "NES", "Advanced Dungeons & Dragons Hillsfar", null },
                    { "19 ", "8462", null, "Strategy", "NES", "Advanced Dungeons & Dragons Pool of Radiance", null },
                    { "20 ", "8464", null, "Action & Adventure", "NES", "Adventure Island", null },
                    { "21 ", "12176", null, "Action & Adventure", "NES", "Adventure Island 3", null },
                    { "22 ", "8465", null, "Action & Adventure", "NES", "Adventure Island II", null },
                    { "23 ", "8466", null, "Action & Adventure", "NES", "Adventures in the Magic Kingdom", null },
                    { "24 ", "8468", null, "Action & Adventure", "NES", "Adventures of Bayou Billy", null },
                    { "25 ", "12119", null, "Action & Adventure", "NES", "Adventures of Captain Comic", null },
                    { "26 ", "12175", null, "Action & Adventure", "NES", "Adventures of Dino Riki", null },
                    { "55 ", "12188", null, "Sports", "NES", "Athletic World", null },
                    { "225", "12212", null, "Action & Adventure", "NES", "Dr Jekyll and Mr Hyde", null },
                    { "56 ", "38009", null, "Sports", "NES", "Athletic World [5 Screw]", null },
                    { "58 ", "12189", null, "Action & Adventure", "NES", "Baby Boomer", null },
                    { "88 ", "8588", null, "Action & Adventure", "NES", "Battletoads and Double Dragon The Ultimate Team", null },
                    { "89 ", "12203", null, "Action & Adventure", "NES", "Bee 52", null },
                    { "90 ", "12204", null, "Action & Adventure", "NES", "BeetleJuice", null },
                    { "91 ", "8600", null, "Fighting", "NES", "Best of the Best Championship Karate", null },
                    { "92 ", "8603", null, "Action & Adventure", "NES", "Bible Adventures", null },
                    { "93 ", "12205", null, "Other", "NES", "Bible Buffet", null },
                    { "94 ", "12106", null, "Action & Adventure", "NES", "Big Nose Freaks Out", null },
                    { "95 ", "39520", null, "Action & Adventure", "NES", "Big Nose Freaks Out [Aladdin]", null },
                    { "96 ", "16129", null, "Action & Adventure", "NES", "Big Nose the Caveman", null },
                    { "97 ", "12206", null, "Action & Adventure", "NES", "Bigfoot", null },
                    { "98 ", "8607", null, "Racing", "NES", "Bill Elliott's NASCAR Challenge", null },
                    { "87 ", "8586", null, "Action & Adventure", "NES", "Battletoads", null },
                    { "99 ", "8606", null, "Action & Adventure", "NES", "Bill and Ted's Excellent Video Game", null },
                    { "101", "12108", null, "Sports", "NES", "Black Bass", null },
                    { "102", "12109", null, "Other", "NES", "Blackjack", null },
                    { "103", "8614", null, "Sports", "NES", "Blades of Steel", null },
                    { "104", "39515", null, "Sports", "NES", "Blades of Steel [Classic Series]", null },
                    { "105", "12110", null, "Action & Adventure", "NES", "Blaster Master", null },
                    { "106", "8625", null, "Sports", "NES", "Blue Marlin", null },
                    { "107", "8627", null, "Action & Adventure", "NES", "Blues Brothers", null },
                    { "108", "8628", null, "Baseball", "NES", "Bo Jackson Baseball", null },
                    { "109", "12111", null, "Action & Adventure", "NES", "Bomberman", null },
                    { "110", "8632", null, "Puzzle", "NES", "Bomberman II", null },
                    { "111", "8636", null, "Action & Adventure", "NES", "Bonk's Adventure", null },
                    { "100", "12107", null, "Action & Adventure", "NES", "Bionic Commando", null },
                    { "86 ", "12202", null, "Action & Adventure", "NES", "Battletank", null },
                    { "85 ", "8582", null, "Strategy", "NES", "Battleship", null },
                    { "84 ", "12201", null, "Action & Adventure", "NES", "Battle of Olympus", null },
                    { "59 ", "12190", null, "Action & Adventure", "NES", "Back to the Future", null },
                    { "60 ", "12191", null, "Action & Adventure", "NES", "Back to the Future II and III", null },
                    { "61 ", "12192", null, "Action & Adventure", "NES", "Bad Dudes", null },
                    { "62 ", "12193", null, "Baseball", "NES", "Bad News Baseball", null },
                    { "63 ", "12194", null, "Fighting", "NES", "Bad Street Brawler", null },
                    { "64 ", "11981", null, "Action & Adventure", "NES", "Balloon Fight", null },
                    { "65 ", "37983", null, "Action & Adventure", "NES", "Balloon Fight [5 Screw]", null },
                    { "66 ", "12195", null, "Sports", "NES", "Bandai Golf Challenge Pebble Beach", null },
                    { "67 ", "13109", null, "Strategy", "NES", "Bandit Kings of Ancient China", null },
                    { "68 ", "8554", null, "Action & Adventure", "NES", "Barbie", null },
                    { "69 ", "8559", null, "RPG", "NES", "Bard's Tale", null },
                    { "70 ", "8560", null, "Other", "NES", "Barker Bill's Trick Shooting", null },
                    { "71 ", "11982", null, "Baseball", "NES", "Baseball", null },
                    { "72 ", "13843", null, "Baseball", "NES", "Baseball Simulator 1.000", null },
                    { "73 ", "12198", null, "Baseball", "NES", "Baseball Stars", null },
                    { "74 ", "8562", null, "Baseball", "NES", "Baseball Stars 2", null },
                    { "75 ", "37966", null, "Baseball", "NES", "Baseball [5 Screw]", null },
                    { "76 ", "8564", null, "Baseball", "NES", "Bases Loaded", null },
                    { "77 ", "8565", null, "Baseball", "NES", "Bases Loaded 2 Second Season", null },
                    { "78 ", "12199", null, "Baseball", "NES", "Bases Loaded 3", null },
                    { "79 ", "8566", null, "Baseball", "NES", "Bases Loaded 4", null },
                    { "80 ", "8574", null, "Action & Adventure", "NES", "Batman Returns", null },
                    { "81 ", "13844", null, "Action & Adventure", "NES", "Batman The Video Game", null },
                    { "82 ", "8570", null, "Action & Adventure", "NES", "Batman: Return of the Joker", null },
                    { "83 ", "12200", null, "Strategy", "NES", "Battle Chess", null },
                    { "57 ", "8541", null, "Action & Adventure", "NES", "Attack of the Killer Tomatoes", null },
                    { "226", "8859", null, "Puzzle", "NES", "Dr. Mario", null },
                    { "227", "8864", null, "Action & Adventure", "NES", "Dragon Fighter", null },
                    { "228", "12213", null, "Action & Adventure", "NES", "Dragon Power", null },
                    { "372", "9169", null, "Other", "NES", "Jeopardy", null },
                    { "373", "9170", null, "Other", "NES", "Jeopardy 25th Anniversary", null },
                    { "374", "9172", null, "Other", "NES", "Jeopardy Jr", null },
                    { "375", "9176", null, "Action & Adventure", "NES", "Jetsons Cogswell's Caper", null },
                    { "376", "9177", null, "Sports", "NES", "Jimmy Connors Tennis", null },
                    { "377", "9179", null, "Action & Adventure", "NES", "Joe and Mac", null },
                    { "378", "12279", null, "Football", "NES", "John Elway's Quarterback", null },
                    { "379", "12280", null, "Basketball", "NES", "Jordan vs Bird One on One", null },
                    { "380", "12281", null, "Action & Adventure", "NES", "Joshua: The Battle of Jericho", null },
                    { "381", "12282", null, "Action & Adventure", "NES", "Journey to Silius", null },
                    { "382", "12283", null, "Action & Adventure", "NES", "Joust", null },
                    { "371", "39519", null, "Action & Adventure", "NES", "Jaws [5 Screw]", null },
                    { "383", "9190", null, "Action & Adventure", "NES", "Jurassic Park", null },
                    { "385", "12285", null, "Fighting", "NES", "Karate Champ", null },
                    { "386", "39518", null, "Sports", "NES", "Karate Champ [5 Screw]", null },
                    { "387", "12286", null, "Action & Adventure", "NES", "Karnov", null },
                    { "388", "9204", null, "Action & Adventure", "NES", "Kick Master", null },
                    { "389", "12287", null, "Action & Adventure", "NES", "Kickle Cubicle", null },
                    { "390", "11996", null, "Action & Adventure", "NES", "Kid Icarus", null },
                    { "391", "38010", null, "Action & Adventure", "NES", "Kid Icarus [5 Screw]", null },
                    { "392", "9205", null, "Action & Adventure", "NES", "Kid Klown in Night Mayor World", null },
                    { "393", "12288", null, "Action & Adventure", "NES", "Kid Kool", null },
                    { "394", "12289", null, "Action & Adventure", "NES", "Kid Niki Radical Ninja", null },
                    { "395", "38041", null, "Action & Adventure", "NES", "Kid Niki Radical Ninja [5 Screw]", null },
                    { "384", "12284", null, "Fighting", "NES", "Kabuki Quantum Fighter", null },
                    { "370", "12278", null, "Action & Adventure", "NES", "Jaws", null },
                    { "369", "9161", null, "Action & Adventure", "NES", "James Bond Jr", null },
                    { "368", "12277", null, "Action & Adventure", "NES", "Jackie Chan's Action Kung Fu", null },
                    { "343", "9133", null, "Action & Adventure", "NES", "Hunt for Red October", null },
                    { "344", "12264", null, "Action & Adventure", "NES", "Hydlide", null },
                    { "345", "11994", null, "Action & Adventure", "NES", "Ice Climber", null },
                    { "346", "37972", null, "Action & Adventure", "NES", "Ice Climber [5 Screw]", null },
                    { "347", "11995", null, "Sports", "NES", "Ice Hockey", null },
                    { "348", "12265", null, "Action & Adventure", "NES", "Ikari Warriors", null },
                    { "349", "12266", null, "Action & Adventure", "NES", "Ikari Warriors II", null },
                    { "350", "12267", null, "Action & Adventure", "NES", "Ikari Warriors III", null },
                    { "351", "38008", null, "Action & Adventure", "NES", "Ikari Warriors [5 Screw]", null },
                    { "352", "12268", null, "Fighting", "NES", "Image Fight", null },
                    { "353", "9138", null, "RPG", "NES", "Immortal", null },
                    { "354", "12269", null, "Action & Adventure", "NES", "Impossible Mission II", null },
                    { "355", "44966", null, "Action & Adventure", "NES", "Impossible Mission II [AVE]", null },
                    { "356", "39510", null, "Action & Adventure", "NES", "Impossible Mission II [SEI]", null },
                    { "357", "9143", null, "Action & Adventure", "NES", "Incredible Crash Dummies", null },
                    { "358", "12270", null, "Action & Adventure", "NES", "Indiana Jones and the Last Crusade", null },
                    { "359", "30748", null, "Action & Adventure", "NES", "Indiana Jones and the Last Crusade [Ubisoft]", null },
                    { "360", "12271", null, "Action & Adventure", "NES", "Indiana Jones and the Temple of Doom", null },
                    { "361", "39513", null, "Action & Adventure", "NES", "Indiana Jones and the Temple of Doom [Tengen]", null },
                    { "362", "12272", null, "Action & Adventure", "NES", "Infiltrator", null },
                    { "363", "12274", null, "RPG", "NES", "Iron Sword Wizards and Warriors II", null },
                    { "364", "12273", null, "Action & Adventure", "NES", "Iron Tank", null },
                    { "365", "12275", null, "Action & Adventure", "NES", "Isolated Warrior", null },
                    { "366", "9155", null, "Sports", "NES", "Jack Nicklaus Golf", null },
                    { "367", "12276", null, "Action & Adventure", "NES", "Jackal", null },
                    { "396", "16437", null, "Action & Adventure", "NES", "King Neptune's Adventure", null },
                    { "342", "9132", null, "Action & Adventure", "NES", "Hudson Hawk", null },
                    { "397", "12290", null, "RPG", "NES", "King of Kings", null },
                    { "399", "12291", null, "RPG", "NES", "King's Quest V", null },
                    { "429", "12307", null, "Action & Adventure", "NES", "Linus Spacehead's Cosmic Adventure", null },
                    { "430", "39522", null, "Action & Adventure", "NES", "Linus Spacehead's Cosmic Adventure [Aladdin]", null },
                    { "431", "12308", null, "Baseball", "NES", "Little League Baseball", null },
                    { "432", "9248", null, "Action & Adventure", "NES", "Little Mermaid", null },
                    { "433", "9249", null, "Action & Adventure", "NES", "Little Nemo The Dream Master", null },
                    { "434", "12309", null, "Action & Adventure", "NES", "Little Ninja Brothers", null },
                    { "435", "9250", null, "Action & Adventure", "NES", "Little Samson", null },
                    { "436", "11998", null, "Action & Adventure", "NES", "Lode Runner", null },
                    { "437", "38024", null, "Action & Adventure", "NES", "Lode Runner [5 Screw]", null },
                    { "438", "9253", null, "Action & Adventure", "NES", "Lone Ranger", null },
                    { "439", "12310", null, "Puzzle", "NES", "Loopz", null },
                    { "428", "12306", null, "Action & Adventure", "NES", "Life Force", null },
                    { "440", "12311", null, "Action & Adventure", "NES", "Low G Man", null },
                    { "442", "38036", null, "Sports", "NES", "Lunar Pool [5 Screw]", null },
                    { "443", "9307", null, "Action & Adventure", "NES", "M.C. Kids", null },
                    { "444", "9387", null, "Other", "NES", "M.U.L.E.", null },
                    { "445", "12386", null, "Action & Adventure", "NES", "MTV Remote Control", null },
                    { "446", "12312", null, "Action & Adventure", "NES", "MUSCLE", null },
                    { "447", "11999", null, "Racing", "NES", "Mach Rider", null },
                    { "448", "37978", null, "Racing", "NES", "Mach Rider [5 Screw]", null },
                    { "449", "12313", null, "Action & Adventure", "NES", "Mad Max", null },
                    { "450", "9275", null, "Sports", "NES", "Magic Darts", null },
                    { "451", "12227", null, "Basketball", "NES", "Magic Johnson's Fast Break", null },
                    { "452", "12314", null, "Action & Adventure", "NES", "Magician", null },
                    { "441", "9260", null, "Sports", "NES", "Lunar Pool", null },
                    { "427", "9245", null, "Action & Adventure", "NES", "Lethal Weapon", null },
                    { "426", "9240", null, "Puzzle", "NES", "Lemmings", null },
                    { "425", "12305", null, "Baseball", "NES", "Legends of the Diamond", null },
                    { "400", "12292", null, "Sports", "NES", "Kings of the Beach", null },
                    { "401", "9213", null, "Action & Adventure", "NES", "Kirby's Adventure", null },
                    { "402", "12293", null, "Action & Adventure", "NES", "Kiwi Kraze", null },
                    { "403", "12294", null, "Sports", "NES", "Klash Ball", null },
                    { "404", "12295", null, "Puzzle", "NES", "Klax", null },
                    { "405", "12296", null, "Racing", "NES", "Knight Rider", null },
                    { "406", "12297", null, "Action & Adventure", "NES", "Krazy Kreatures", null },
                    { "407", "12298", null, "Action & Adventure", "NES", "Krion Conquest", null },
                    { "408", "9217", null, "Puzzle", "NES", "Krusty's Fun House", null },
                    { "409", "12299", null, "Fighting", "NES", "Kung Fu", null },
                    { "410", "12300", null, "Fighting", "NES", "Kung Fu Heroes", null },
                    { "411", "37973", null, "Action & Adventure", "NES", "Kung Fu [5 Screw]", null },
                    { "412", "9242", null, "Strategy", "NES", "L'Empereur", null },
                    { "413", "9222", null, "Action & Adventure", "NES", "Laser Invasion", null },
                    { "414", "19472", null, "Accessories", "NES", "Laserscope", null },
                    { "415", "9224", null, "Action & Adventure", "NES", "Last Action Hero", null },
                    { "416", "12301", null, "Action & Adventure", "NES", "Last Starfighter", null },
                    { "417", "12302", null, "Sports", "NES", "Lee Trevino's Fighting Golf", null },
                    { "418", "12303", null, "RPG", "NES", "Legacy of the Wizard", null },
                    { "419", "11997", null, "Action & Adventure", "NES", "Legend of Kage", null },
                    { "420", "38018", null, "Action & Adventure", "NES", "Legend of Kage [5 Screw]", null },
                    { "421", "9236", null, "Strategy", "NES", "Legend of Zelda", null },
                    { "422", "38020", null, "Action & Adventure", "NES", "Legend of Zelda [5 Screw]", null },
                    { "423", "38512", null, "Action & Adventure", "NES", "Legend of Zelda [Gray Cart]", null },
                    { "424", "12304", null, "Other", "NES", "Legendary Wings", null },
                    { "398", "9212", null, "Strategy", "NES", "King's Knight", null },
                    { "907", "10236", null, "Action & Adventure", "NES", "Zen Intergalactic Ninja", null },
                    { "341", "14931", null, "Action & Adventure", "NES", "Hot Slots", null },
                    { "339", "9121", null, "Action & Adventure", "NES", "Hook", null },
                    { "258", "12226", null, "Action & Adventure", "NES", "Fantasy Zone", null },
                    { "259", "8939", null, "RPG", "NES", "Faria", null },
                    { "260", "13717", null, "Action & Adventure", "NES", "Faxanadu", null },
                    { "261", "8948", null, "Action & Adventure", "NES", "Felix the Cat", null },
                    { "262", "8949", null, "Racing", "NES", "Ferrari Grand Prix Challenge", null },
                    { "263", "8950", null, "Action & Adventure", "NES", "Fester's Quest", null },
                    { "264", "8970", null, "RPG", "NES", "Final Fantasy", null },
                    { "265", "8975", null, "Puzzle", "NES", "Fire 'N Ice", null },
                    { "266", "12229", null, "Action & Adventure", "NES", "Firehawk", null },
                    { "267", "12230", null, "Other", "NES", "Fisher Price I Can Remember", null },
                    { "268", "12231", null, "Other", "NES", "Fisher Price Perfect Fit", null },
                    { "257", "39521", null, "Action & Adventure", "NES", "Fantastic Adventures of Dizzy [Aladdin]", null },
                    { "269", "8976", null, "Action & Adventure", "NES", "Fisher-Price Firehouse Rescue", null },
                    { "271", "8981", null, "Action & Adventure", "NES", "Flight of the Intruder", null },
                    { "272", "13107", null, "Action & Adventure", "NES", "Flintstones Surprise at Dinosaur Peak", null },
                    { "273", "8983", null, "Action & Adventure", "NES", "Flintstones The Rescue of Dino and Hoppy", null },
                    { "274", "12234", null, "Action & Adventure", "NES", "Flying Dragon", null },
                    { "275", "12235", null, "Action & Adventure", "NES", "Flying Warriors", null },
                    { "276", "14550", null, "Racing", "NES", "Formula One Built To Win", null },
                    { "277", "12236", null, "Action & Adventure", "NES", "Frankenstein the Monster Returns", null },
                    { "278", "12237", null, "Action & Adventure", "NES", "Freedom Force", null },
                    { "279", "12238", null, "Action & Adventure", "NES", "Friday the 13th", null },
                    { "280", "12239", null, "Action & Adventure", "NES", "Fun House", null },
                    { "281", "12240", null, "Action & Adventure", "NES", "G.I. Joe: A Real American Hero", null },
                    { "270", "12232", null, "Fighting", "NES", "Fist of the North Star", null },
                    { "256", "12225", null, "Action & Adventure", "NES", "Fantastic Adventures of Dizzy", null },
                    { "255", "12224", null, "Sports", "NES", "Family Fun Fitness Stadium Events", null },
                    { "254", "45059", null, "Controllers", "NES", "Family Fun Fitness Pad", null },
                    { "229", "12214", null, "Action & Adventure", "NES", "Dragon Spirit", null },
                    { "230", "12216", null, "RPG", "NES", "Dragon Warrior", null },
                    { "231", "12215", null, "RPG", "NES", "Dragon Warrior II", null },
                    { "232", "8868", null, "RPG", "NES", "Dragon Warrior III", null },
                    { "233", "8869", null, "RPG", "NES", "Dragon Warrior IV", null },
                    { "234", "12217", null, "Action & Adventure", "NES", "Dragon's Lair the Legend", null },
                    { "235", "12218", null, "Other", "NES", "Duck Hunt", null },
                    { "236", "37976", null, "Action & Adventure", "NES", "Duck Hunt [5 Screw]", null },
                    { "237", "12219", null, "Action & Adventure", "NES", "Duck Tales", null },
                    { "238", "8878", null, "Action & Adventure", "NES", "Duck Tales 2", null },
                    { "239", "34156", null, "Action & Adventure", "NES", "Duck Tales Gold Cartridge", null },
                    { "240", "12220", null, "Action & Adventure", "NES", "Dudes with Attitude", null },
                    { "241", "12221", null, "RPG", "NES", "Dungeon Magic", null },
                    { "242", "12222", null, "Baseball", "NES", "Dusty Diamond's All-Star Softball", null },
                    { "243", "8889", null, "Action & Adventure", "NES", "Dynowarz The Destruction of Spondylus", null },
                    { "244", "11989", null, "Puzzle", "NES", "Elevator Action", null },
                    { "245", "38017", null, "Action & Adventure", "NES", "Elevator Action [5 Screw]", null },
                    { "246", "8906", null, "Racing", "NES", "Eliminator Boat Duel", null },
                    { "247", "11990", null, "Racing", "NES", "Excitebike", null },
                    { "248", "37977", null, "Racing", "NES", "Excitebike [5 Screw]", null },
                    { "249", "12223", null, "RPG", "NES", "Exodus Journey to the Promised Land", null },
                    { "250", "8928", null, "Other", "NES", "F-117A Stealth Fighter", null },
                    { "251", "19760", null, "Action & Adventure", "NES", "F-15 City War", null },
                    { "252", "8929", null, "Action & Adventure", "NES", "F-15 Strike Eagle", null },
                    { "253", "8935", null, "Other", "NES", "Family Feud", null },
                    { "282", "9034", null, "Action & Adventure", "NES", "GI Joe The Atlantis Factor", null },
                    { "340", "12263", null, "Basketball", "NES", "Hoops", null },
                    { "283", "32330", null, "Action & Adventure", "NES", "Galactic Crusader", null },
                    { "285", "12242", null, "Action & Adventure", "NES", "Galaxy 5000", null },
                    { "315", "11993", null, "Other", "NES", "Gradius", null },
                    { "316", "37999", null, "Other", "NES", "Gradius [5 Screw]", null },
                    { "317", "9063", null, "Puzzle", "NES", "Great Waldo Search", null },
                    { "318", "9068", null, "Sports", "NES", "Greg Norman's Golf Power", null },
                    { "319", "12252", null, "Action & Adventure", "NES", "Gremlins 2", null },
                    { "320", "12253", null, "Action & Adventure", "NES", "Guerrilla War", null },
                    { "321", "12254", null, "Action & Adventure", "NES", "Gumshoe", null },
                    { "322", "37990", null, "Other", "NES", "Gumshoe [5 Screw]", null },
                    { "323", "12255", null, "Action & Adventure", "NES", "Gun-Nac", null },
                    { "324", "12256", null, "Action & Adventure", "NES", "Gun.Smoke", null },
                    { "325", "12257", null, "Action & Adventure", "NES", "Gyromite", null },
                    { "314", "39516", null, "Action & Adventure", "NES", "Gotcha [5 Screw]", null },
                    { "326", "37970", null, "Other", "NES", "Gyromite [5 Screw]", null },
                    { "328", "12258", null, "Action & Adventure", "NES", "Gyruss", null },
                    { "329", "12259", null, "Basketball", "NES", "Harlem Globetrotters", null },
                    { "330", "9097", null, "Puzzle", "NES", "Hatris", null },
                    { "331", "12260", null, "Action & Adventure", "NES", "Heavy Barrel", null },
                    { "332", "12261", null, "Action & Adventure", "NES", "Heavy Shreddin'", null },
                    { "333", "9109", null, "Arcade", "NES", "High Speed", null },
                    { "334", "12262", null, "Other", "NES", "Hogan's Alley", null },
                    { "335", "37971", null, "Other", "NES", "Hogan's Alley [5 Screw]", null },
                    { "336", "9115", null, "Other", "NES", "Hollywood Squares", null },
                    { "337", "9117", null, "Action & Adventure", "NES", "Home Alone", null },
                    { "338", "9119", null, "Action & Adventure", "NES", "Home Alone 2 Lost In New York", null },
                    { "327", "37958", null, "Action & Adventure", "NES", "Gyromite [ROB Bundle]", null },
                    { "313", "12251", null, "Action & Adventure", "NES", "Gotcha", null },
                    { "312", "12250", null, "Action & Adventure", "NES", "Golgo 13 Top Secret Episode", null },
                    { "311", "37969", null, "Sports", "NES", "Golf [5 Screw]", null },
                    { "286", "52012", null, "Sports", "NES", "Galf", null },
                    { "287", "52013", null, "Sports", "NES", "Galf [White]", null },
                    { "288", "13192", null, "Accessories", "NES", "Game Genie", null },
                    { "289", "37040", null, "Accessories", "NES", "Game Genie Top Loader Adaptor", null },
                    { "290", "9012", null, "Action & Adventure", "NES", "Gargoyle's Quest II The Demon Darkness", null },
                    { "291", "12243", null, "Action & Adventure", "NES", "Gauntlet", null },
                    { "292", "9013", null, "Action & Adventure", "NES", "Gauntlet II", null },
                    { "293", "39511", null, "Action & Adventure", "NES", "Gauntlet [Gray Cart]", null },
                    { "294", "9018", null, "Strategy", "NES", "Gemfire", null },
                    { "295", "12244", null, "Action & Adventure", "NES", "Genghis Khan", null },
                    { "296", "9025", null, "Sports", "NES", "George Foreman's KO Boxing", null },
                    { "297", "9029", null, "RPG", "NES", "Ghost Lion", null },
                    { "298", "12245", null, "Action & Adventure", "NES", "Ghostbusters", null },
                    { "299", "9032", null, "Action & Adventure", "NES", "Ghostbusters II", null },
                    { "300", "11992", null, "Action & Adventure", "NES", "Ghosts 'n Goblins", null },
                    { "301", "37998", null, "Action & Adventure", "NES", "Ghosts 'n Goblins [5 Screw]", null }
                });

            migrationBuilder.InsertData(
                table: "Games",
                columns: new[] { "Id", "ApiGameId", "CoverURL", "Genre", "SystemId", "Title", "Upc" },
                values: new object[,]
                {
                    { "302", "9033", null, "Action & Adventure", "NES", "Ghoul School", null },
                    { "303", "12247", null, "Action & Adventure", "NES", "Gilligan's Island", null },
                    { "304", "12248", null, "Soccer", "NES", "Goal", null },
                    { "305", "9039", null, "Soccer", "NES", "Goal Two", null },
                    { "306", "12249", null, "Action & Adventure", "NES", "Godzilla", null },
                    { "307", "9042", null, "Strategy", "NES", "Godzilla 2", null },
                    { "308", "9045", null, "Sports", "NES", "Gold Medal Challenge '92", null },
                    { "309", "9050", null, "Sports", "NES", "Golf", null },
                    { "310", "9051", null, "Sports", "NES", "Golf Grand Slam", null },
                    { "284", "11991", null, "Other", "NES", "Galaga: Demons of Death", null },
                    { "908", "10239", null, "Other", "NES", "Zombie Nation", null }
                });

            migrationBuilder.CreateIndex(
                name: "IX_UserGames_GameId1",
                table: "UserGames",
                column: "GameId1");

            migrationBuilder.CreateIndex(
                name: "IX_UserGames_UserId",
                table: "UserGames",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Wishlists_GameId1",
                table: "Wishlists",
                column: "GameId1");

            migrationBuilder.CreateIndex(
                name: "IX_Wishlists_UserId",
                table: "Wishlists",
                column: "UserId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserGames");

            migrationBuilder.DropTable(
                name: "Wishlists");

            migrationBuilder.DropTable(
                name: "Games");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
